### ISSUE TITLE
Investigate: contract not rebinding when quickstart container already has contracts deployed

### ISSUE THREAD

**Issue by elizabethengelman** [loambuild/loam#145]
I have noticed the following scenario, and I think that it's worth looking into:

- When I already have my quickstart container running 
- And have already deployed my loam contracts
- When I try to create a new project sometimes the contracts aren't re-bound to ts clients in the new project

**Comment by BlaineHeffron** [comment]
When you notice it doesn't rebind, do you see if it gets to the `stellar contract bindings typescript` call? Maybe its erroring out before that? Or is it the bindings call thats failing?

**Comment by elizabethengelman** [comment]
Good question - I'm not seeing errors per se, but here are the repro steps. I'm also wondering if this is an edge case that we shouldn't be too concerned about. 🤷‍♀️


Repro steps:

- start docker desktop
- start quickstart `soroban network container start local`
#### new-project
- init a new project: `loam init new-project`
- build: `cd new-project && loam dev --build-clients`
- this works and both example contracts are installed, bound and imported, and the ts files are in `new-project/src/contracts`
```
🌐 using network at http://localhost:8000/rpc
ℹ️ account "me" already exists, skipping key creation
📲 installing "example_core" wasm bytecode on-chain...
    ↳ hash: f491c824a15c7ee3548a5de2b20c987a4a3e6d73aed5082187e5b1de466091e8
🔄 Updating contract "example_core"
🪞 instantiating "example_core" smart contract
    ↳ contract_id: CCOQBAZKJ4DB7C7XB6FNU6FDUC6ICUKEUGAVJ65E4ZLZZKBSEH2FXS7L
🎭 binding "example_core" contract

added 29 packages, and audited 31 packages in 3s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> example_core@0.0.0 build
> tsc

🍽️ importing "example_core" contract
📲 installing "example_status_message" wasm bytecode on-chain...
    ↳ hash: 195a674c9770ce3bfcd5c7db42910e23779b8d177c5980b08bf97d04fec341b3
🔄 Updating contract "example_status_message"
🪞 instantiating "example_status_message" smart contract
    ↳ contract_id: CB7KYIO3MU6RDENQHIN4XIXNOLWYQWD5F3SJFCFDFYVAAPLLFBVB6YQW
🎭 binding "example_status_message" contract

added 1 package, and audited 33 packages in 1s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> example_status_message@0.0.0 build
> tsc

🍽️ importing "example_status_message" contract
Watching for changes. Press Ctrl+C to stop.
```
#### another-new-project
- init another new project: `loam init another-new-project`
- build new project: `cd another-new-project && loam dev --build-clients`
- since the example contracts are both already deployed to the chain, the process finds the contract hashes and does not re-build the ts clients:
```
🌐 using network at http://localhost:8000/rpc
ℹ️ account "me" already exists, skipping key creation
📲 installing "example_core" wasm bytecode on-chain...
    ↳ hash: f491c824a15c7ee3548a5de2b20c987a4a3e6d73aed5082187e5b1de466091e8
✅ Contract "example_core" is up to date
📲 installing "example_status_message" wasm bytecode on-chain...
    ↳ hash: 195a674c9770ce3bfcd5c7db42910e23779b8d177c5980b08bf97d04fec341b3
✅ Contract "example_status_message" is up to date
Watching for changes. Press Ctrl+C to stop.
```

**Comment by BlaineHeffron** [comment]
Interesting, it looks like its finding the alias even though the working directory is different. It appears its always saving the alias to `~/.soroban` even if I pass the `workspace_dir` to `config::locator::Args.config_dir`.
