### ISSUE TITLE
Update fungible token subcontract & implementation for latest standard

### ISSUE THREAD

**Issue by chadoh** [loambuild/loam#150]
The [official Soroban FT standard](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0041.md) has evolved since @willemneal first authored `loam-subcontract-ft` and its implementation in the examples folder.

We need to update these to match the latest implementation.

Let's also update the `trait` to include all the comments from the spec, as well as linking to the spec and mentioning that it's SEP41 in the docs for the main `MyFungible` trait.

**Comment by BlaineHeffron** [comment]
Closed via https://github.com/loambuild/loam/pull/155
