### ISSUE TITLE
Need to build in specified order

### ISSUE THREAD

**Issue by chadoh** [loambuild/loam#153]
Right now when you `loam build` you don't know what order contracts will be built in.

If the second contract specified in the `environments.toml` relies on the first, this causes big problems.

**Comment by willemneal** [comment]
Do you have a case of this happening? The contracts should build in the order of dependencies. If there is an issue it's because the contracts don't specify the other in the cargo.toml.

**Comment by BlaineHeffron** [comment]
resolved https://github.com/loambuild/loam/pull/160
