### ISSUE TITLE
build-clients: run `init` commands for contracts

### ISSUE THREAD

**Issue by chadoh** [loambuild/loam#74]
Follow-up to #73 

If environments.toml [specifies an `init` script](https://github.com/loambuild/frontend/blob/7df7587b5d3c87d113074d1186eff61bd8ae9c1e/environments.toml#L41-L53) for a contract, then we need to run that script, as the default account, when the contract is first deployed. If the contract has already been deployed (that is, if we already have an alias saved), then we should assume that the `init` script was already run.

Some open design considerations:

1. Maybe we should have a way to run the init script for a specific contract, so people can retry that part of the `build` run if their script is malformed? Not sure what this would look like. As of #58, you can't run `build-clients` directly, it gets run at the end of `build`. So would "just run init for contract-a" functionality get added to `build`? Not sure. Maybe this is too complicated, and we should just tell people to remove the alias for the problem contract, and re-run `loam build`, which is otherwise idempotent.
2. Maybe we should continue with the rest of the `build_clients` logic, even if one of these fails, and mention how to re-run just this `init` logic, based on whatever we decide above?

**Comment by BlaineHeffron** [comment]
For 1: I have 2 ideas, first is a `--force-init <name>` arg to `build`. The other is have a separate command, `loam-init <name>`

For 2: We could add a ` --continue-on-error    Continue building and initializing other contracts if one fails` command. Perhaps this defaults to true. Then when this is true we will collect the names of the contracts whose initialization failed and list the appropriate command to rebuild (ie `loam-init <name>`) depending on what we decide for 1. (or we could implement both options in 1)

**Comment by chadoh** [comment]
Since the whole thing is more-or-less idempotent, I think maybe we just do 2, and mention to re-run the whole `loam build` process if one of the `contract init` steps fails. I think that keeps it pretty simple?

The SIMPLEST thing to do would be neither of them. Maybe we just start there and see how big of a problem this is, unless you think `2` is pretty easy. We could also make a follow-up issue for `2`.

**Comment by BlaineHeffron** [comment]
2 sounds pretty easy but I'll know more once I'm implementing it.
