### ISSUE TITLE
build-clients: add `contracts.cargo-workspace` shortcut

### ISSUE THREAD

**Issue by chadoh** [loambuild/loam#75]
In our [example `environments.toml` file](https://github.com/loambuild/frontend/blob/7df7587b5d3c87d113074d1186eff61bd8ae9c1e/environments.toml#L26), we say in development and testing environments, you can do this:

```toml
[development.contracts]
# Auto-build, -deploy, -bind, and -import all contracts in Cargo workspace
# Only supported in development & test environments
cargo-workspace = true
```

The initial implementation of the `build-clients` logic in #42 did not support this. You need to explicitly list each of the contracts.

## Design questions

`development.contracts` currently specifies a vector of contracts. This would change one of them to be a special, reserved string, `"cargo-workspace"`. This means you would not be able to have a contract named `cargo-workspace`, which—maybe that's fine? Seems an unlikely contract name. And also, the actual contracts specified here don't work if you use dashes. The generated wasm files use underscores, and you need to match those. But maybe that's a bug? We probably wouldn't want `cargo-workspace` to be the reserved word and `cargo_workspace` to refer to an actual contract.

All this to say: maybe we don't want the reserved word. Maybe instead we:

- Just always assume you want to generate clients for all workspace contracts, if you have an environments.toml file.
- Add a different key, like `development.contracts-from-workspace = true`. 
- A combination of the two. Make `development.contracts-from-workspace` default to `true`, but allow overriding to `false`. Is this unnecessary at this point?

I personally lean toward the first approach. We could add the `contracts-from-workspace` flag later, if we discover situations where it would be useful to have an `environments.toml` file and _not_ build clients for all workspace contracts.

**Comment by BlaineHeffron** [comment]
IMO I like the simplest option here which is to just auto build clients for all workspace contracts. Like you said, if there are use cases for not doing so we can add a flag later.
