### ISSUE TITLE
`loam init`: replace `soroban-sdk` dep with `loam-sdk`

### ISSUE THREAD

**Issue by chadoh** [loambuild/loam#99]
In Cargo.toml file created in new project, we need to specify `loam-sdk`, not `soroban-sdk`. We also need to specify `loam-subcontract-core` (though maybe someday we will re-export this from `loam-sdk`).

We also need to make sure this works with `soroban contract init`, which seems more tricky! Go ahead and explore how we might want to approach this and make a suggestion or two!

**Comment by elizabethengelman** [comment]
some notes as I research this:

- `stellar contract init -f <fe-template-url>` does not overwrite the [base init template Cargo.toml](https://github.com/stellar/stellar-cli/blob/main/cmd/soroban-cli/src/utils/contract-init-template/Cargo.toml.removeextension) with the fe template's Cargo.toml. 
    - At the moment this makes sense, for `soroban-astro-template` since it is basically the same as the [base init Cargo.toml](https://github.com/stellar/stellar-cli/blob/main/cmd/soroban-cli/src/utils/contract-init-template/Cargo.toml.removeextension) file (except that `soroban-astro-template`'s soroban-sdk version is a bit out of date and probably should be updated). 
    - This doesn't work for `loam init` (which is running `stellar init` under the hood) because it keeps `stellar contract init`'s Cargo.toml which has `soroban-sdk` as it's only workspace dep and we need `loam-sdk`
- Idea: Overwrite or merge the Cargo.toml files from the FE template and the base init template.
    - The easiest place to make this change is in `stellar contract init`. Does this make sense for other FE template scenarios? Or do we need to find a way to do this in `loam` instead? 🤔

**Comment by elizabethengelman** [comment]
@chadoh could you say a bit more about what you mean when you say that this should also work with `soroban contract init`? Do you mean that we will want to be able to pass our loam frontend template to `soroban contract init` like this: `soroban contract init ./test-project -f https://github.com/loambuild/frontend`?

**Comment by chadoh** [comment]
> Do you mean that we will want to be able to pass our loam frontend template to `soroban contract init` like this: `soroban contract init ./test-project -f https://github.com/loambuild/frontend`?

Yes, exactly.

> Idea: Overwrite or merge the workspace Cargo.toml file from the FE template and the base init template.

I think this is what we should probably do for now. Seems more straightforward than the backend template idea.

Note that loambuild/frontend is set up to develop on the `dev` branch, and push everything to `main` via a GitHub action that uses [the publish.sh script](https://github.com/loambuild/frontend/blob/dev/publish.sh). I actually thought `Cargo.toml` and `Cargo.lock` were in that script, but it looks like we forgot them. Which is good news for this task, since you'll want both Cargo.toml files there. We should still probably circle back and remove `Cargo.toml` from soroban-astro-template at some point.

> One way we can solve this is by creating a loam-specific examples repo, and requiring that loam init uses those examples instead of https://github.com/stellar/soroban-examples

Yes, this is one of the milestones for our next grant cycle! Haven't made an issue for it yet, but we definitely want that. If you use `stellar contract init` you would still end up with `stellar/soroban-examples`, but if you use `loam init` then you would get loam examples.

**Comment by chadoh** [comment]
Actually, merging the Cargo.toml files is tricky. And we're not really sure if other people will want it. It's hard to justify from the Stellar CLI side.

Also, if you use `stellar contract init` and get example contracts from `stellar/soroban-examples`, then you don't need a different Cargo.toml. You only need it with `loam init`, because that gives you example contracts that use Loam SDK.

So let's just do this on the Loam side. When you run `loam init`, it needs to manually overwrite `Cargo.toml` with the one we want, which should probably come from the frontend repo, but could be embedded in Loam CLI the same way the examples are, for now.

**Comment by elizabethengelman** [comment]
> Actually, merging the Cargo.toml files is tricky. And we're not really sure if other people will want it. It's hard to justify from the Stellar CLI side.

It is tricky. The naive way I spiked it out in https://github.com/AhaLabs/stellar-cli/pull/24 was to just always overwrite the existing workspace Cargo.toml with the frontend template's Cargo.toml... but that doesn't seem right because as you said we aren't sure that other people actual want that. I think that circling back and removing the Cargo.toml from `soroban-astro-template` would be good - just to reduce confusion. (#future-todo) <- just a reminder for myself to add an issue 

Ok, so I'll plan to do this on the loam side:
- one way would be to re-clone the FE template repo, and then overwrite the existing workspace Cargo.toml file (we need to re-clone it, because `soroban contract init` cleans it's temp file up after it finishes).
- Or, we can just expect that the workspace Cargo.toml file will have `soroban-sdk` as a workspace dep, and replace that with `loam-sdk` and add `loam-subcontract-core`. Though this isn't real elegant, and may be brittle, it is probably the most straightforward way for now. Especially since we know that the workspace Cargo.toml will always have `soroban-sdk` in it, unless https://github.com/stellar/stellar-cli/blob/main/cmd/soroban-cli/src/utils/contract-init-template/Cargo.toml.removeextension#L8 changes

**Comment by elizabethengelman** [comment]
> Note that loambuild/frontend is set up to develop on the dev branch, and push everything to main via a GitHub action that uses the publish.sh script. I actually thought Cargo.toml and Cargo.lock were in that script, but it looks like we forgot them. Which is good news for this task, since you'll want both Cargo.toml files there. 

Ah, thank you for that reminder. I think that the Cargo.toml and Cargo.lock files are included still, since we have the wildcard there... but I'll double check.

**Comment by elizabethengelman** [comment]
wip prs:
- https://github.com/loambuild/frontend/pull/5
- https://github.com/loambuild/loam/pull/120

I'll test and clean these up tomorrow.
